name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Make script executable
      run: chmod +x hello.sh

    - name: Run Hello Script
      run: ./hello.sh
